# Connectors & Cuswords

connectors = ['a', 'abaft', 'aboard', 'about', 'above', 'absent',
              'absolutely', 'according', 'across', 'afore', 'after', 'again',
              'against', 'ahead', 'aint', 'all', 'along', 'alongside', 'alot',
              'although', 'am', 'amid', 'amidst', 'among', 'amongst', 'amp',
              'an', 'and', 'another', 'any', 'apart', 'apropos', 'are', 'around',
              'as', 'aside', 'astride', 'at', 'ata', 'athwart', 'atop', 'back',
              'barring', 'basically', 'be', 'because', 'become', 'been',
              'before', 'behind', 'being', 'below', 'beneath', 'beside',
              'besides', 'best', 'between', 'beyond', 'bit', 'both', 'but',
              'by', 'can', 'cant', 'circa', 'completely', 'concerning',
              'couple', 'despite', 'did', 'do', 'does', 'doesnt', 'doing',
              'don', 'dont', 'down', 'during', 'each', 'either', 'enough',
              'etc', 'ever', 'every', 'except', 'excessively', 'excluding',
              'extremely', 'failing', 'faq', 'few', 'following', 'for',
              'from', 'further', 'get', 'given', 'got', 'had', 'half',
              'has', 'have', 'having', 'he', 'her', 'here', 'hers', 'herself',
              'him', 'himself', 'his', 'how', 'i', 'if', 'ill', 'in', 'inc',
              'including', 'inside', 'instead', 'into', 'is', 'it', 'its',
              'itself', 'ive', 'just', 'lack', 'last', 'lest', 'like', 'little',
              'llc', 'llp', 'lol', 'lot', 'lots', 'many', 'me',
              'mid', 'midst', 'minus', 'modulo', 'more', 'most', 'much', 'my',
              'myself', 'near', 'need', 'neither', 'never', 'next', 'no', 'none',
              'nor', 'not', 'now', 'of', 'off', 'on', 'once', 'one', 'only',
              'onto', 'opposite', 'or', 'other', 'our', 'ours', 'ourselves',
              'out', 'over', 'own', 'per', 'prior', 'put', 'retweet', 'same',
              'seen', 'several', 'she', 'should', 'since', 'so', 'some',
              'subsequent', 'such', 'ten', 'than', 'that', 'thats', 'the',
              'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these',
              'they', 'this', 'those', 'though', 'through', 'throughout', 'thru',
              'thruout', 'till', 'to', 'too', 'toward', 'towards', 'under',
              'underneath', 'unlike', 'until', 'unto', 'up', 'upon', 'versus',
              'very', 'via', 'vice', 'was', 'we', 'well', 'were', 'what', 'when',
              'where', 'whether', 'which', 'while', 'who', 'whom', 'whose',
              'why', 'will', 'with', 'within', 'without', 'worth', 'would',
              'yet', 'you', 'your', 'youre', 'yours', 'yourself', 'yourselves']

cuswords = ['ass',  'asshole', 'cunt', 'dick', 'dike', 'dildo',
            'douche', 'dyke', 'fag', 'fuck', 'fucked', 'fucker', 'fuckface',
            'gay', 'goddamn', 'goddamnit', 'gook', 'gringo', 'handjob',
            'ho', 'hoe', 'homo', 'honkey', 'jap', 'jerkoff', 'jizz',
            'kike', 'kooch', 'kunt', 'kyke', 'mothafucka', 'mothafuckin',
            'motherfucker', 'motherfucking', 'negro', 'nigga', 'nigger',
            'niggers', 'pecker', 'penis', 'piss', 'poon', 'poonani',
            'poonany', 'poontang', 'porchmonkey', 'pussies', 'pussy',
            'sandnigger', 'schlong', 'shit', 'shithead', 'shithole',
            'shitting', 'shitty', 'slut', 'tit', 'tits', 'twat',
            'wanker', 'wetback', 'whore', 'whorebag', 'wop', 'whop']
